version: '3'
services:
  namenode:
    image: sequenceiq/hadoop-docker:2.7.0
    container_name: namenode
    ports:
      - "50070:50070"
      - "9000:9000"
    command: /etc/bootstrap.sh -d
  app:
    build: .
    container_name: python_hadoop
    depends_on:
      - namenode